version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install dotenv-cli --save-dev
  pre_build:
    commands:
      - echo Loading environment variables...
      - npx dotenv -e .env -- echo Environment variables loaded
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application...
      - npx dotenv -e .env -- npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

  discard-paths: yes
