version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Placeholder for installation commands
  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # Placeholder for pre-build commands
  build:
    commands:
      - echo "Building the project..."
      # Placeholder for build commands
  post_build:
    commands:
      - echo "Running post-build steps..."
      # Placeholder for post-build commands

artifacts:
  files:
    - '**/*'
  discard-paths: yes
