version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Loading environment variables...
      - source .env
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

  discard-paths: yes
